/* tslint:disable */
/* eslint-disable */
/**
 * Store Management API
 * API for managing store operations including inventory, orders, and customers
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderItemRequest } from './order-item-request';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderStatus } from './order-status';
// May contain unused imports in some cases
// @ts-ignore
import type { PaymentMethod } from './payment-method';

export interface OrderRequest {
    'customerId'?: number | null;
    'userId'?: number;
    'promotionId'?: number | null;
    'date'?: string;
    'paymentMethod'?: PaymentMethod;
    'totalAmount'?: number;
    'discountAmount'?: number;
    'orderStatus'?: OrderStatus;
    'listItems'?: Array<OrderItemRequest> | null;
}



