/* tslint:disable */
/* eslint-disable */
/**
 * Store Management API
 * API for managing store operations including inventory, orders, and customers
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderResponse } from './order-response';

export interface PagedResponseOrderResponse {
    'items'?: Array<OrderResponse> | null;
    'pageNumber'?: number;
    'pageSize'?: number;
    'totalItems'?: number;
    'totalPages'?: number;
    'hasPreviousPage'?: boolean;
    'hasNextPage'?: boolean;
}

