/* tslint:disable */
/* eslint-disable */
/**
 * Store Management API
 * API for managing store operations including inventory, orders, and customers
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ResponseObject } from '../models';
// @ts-ignore
import type { ResponsePagedResponseProductResponse } from '../models';
// @ts-ignore
import type { ResponseProductResponse } from '../models';
/**
 * ProductApi - axios parameter creator
 */
export const ProductApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} productName 
         * @param {number} price 
         * @param {number} [categoryId] 
         * @param {number} [supplierId] 
         * @param {string} [barcode] 
         * @param {string} [unit] 
         * @param {string} [imageUrl] 
         * @param {File} [imageFile] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProduct: async (productName: string, price: number, categoryId?: number, supplierId?: number, barcode?: string, unit?: string, imageUrl?: string, imageFile?: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productName' is not null or undefined
            assertParamExists('createProduct', 'productName', productName)
            // verify required parameter 'price' is not null or undefined
            assertParamExists('createProduct', 'price', price)
            const localVarPath = `/api/Product`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


            if (productName !== undefined) { 
                localVarFormParams.append('ProductName', productName as any);
            }
    
            if (categoryId !== undefined) { 
                localVarFormParams.append('CategoryId', categoryId as any);
            }
    
            if (supplierId !== undefined) { 
                localVarFormParams.append('SupplierId', supplierId as any);
            }
    
            if (barcode !== undefined) { 
                localVarFormParams.append('Barcode', barcode as any);
            }
    
            if (price !== undefined) { 
                localVarFormParams.append('Price', price as any);
            }
    
            if (unit !== undefined) { 
                localVarFormParams.append('Unit', unit as any);
            }
    
            if (imageUrl !== undefined) { 
                localVarFormParams.append('ImageUrl', imageUrl as any);
            }
    
            if (imageFile !== undefined) { 
                localVarFormParams.append('ImageFile', imageFile as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProduct: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteProduct', 'id', id)
            const localVarPath = `/api/Product/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [productName] 
         * @param {string} [barcode] 
         * @param {Array<number>} [categoryIds] 
         * @param {Array<number>} [supplierIds] 
         * @param {number} [minPrice] 
         * @param {number} [maxPrice] 
         * @param {boolean} [inStock] 
         * @param {number} [pageNumber] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        filterProducts: async (productName?: string, barcode?: string, categoryIds?: Array<number>, supplierIds?: Array<number>, minPrice?: number, maxPrice?: number, inStock?: boolean, pageNumber?: number, pageSize?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Product/filter`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (productName !== undefined) {
                localVarQueryParameter['ProductName'] = productName;
            }

            if (barcode !== undefined) {
                localVarQueryParameter['Barcode'] = barcode;
            }

            if (categoryIds) {
                localVarQueryParameter['CategoryIds'] = categoryIds;
            }

            if (supplierIds) {
                localVarQueryParameter['SupplierIds'] = supplierIds;
            }

            if (minPrice !== undefined) {
                localVarQueryParameter['MinPrice'] = minPrice;
            }

            if (maxPrice !== undefined) {
                localVarQueryParameter['MaxPrice'] = maxPrice;
            }

            if (inStock !== undefined) {
                localVarQueryParameter['InStock'] = inStock;
            }

            if (pageNumber !== undefined) {
                localVarQueryParameter['PageNumber'] = pageNumber;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['PageSize'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [pageNumber] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllProducts: async (pageNumber?: number, pageSize?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Product`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (pageNumber !== undefined) {
                localVarQueryParameter['pageNumber'] = pageNumber;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} barcode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProductByBarcode: async (barcode: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'barcode' is not null or undefined
            assertParamExists('getProductByBarcode', 'barcode', barcode)
            const localVarPath = `/api/Product/barcode/{barcode}`
                .replace(`{${"barcode"}}`, encodeURIComponent(String(barcode)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProductById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getProductById', 'id', id)
            const localVarPath = `/api/Product/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {string} productName 
         * @param {number} price 
         * @param {number} [categoryId] 
         * @param {number} [supplierId] 
         * @param {string} [barcode] 
         * @param {string} [unit] 
         * @param {string} [imageUrl] 
         * @param {File} [imageFile] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProduct: async (id: number, productName: string, price: number, categoryId?: number, supplierId?: number, barcode?: string, unit?: string, imageUrl?: string, imageFile?: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateProduct', 'id', id)
            // verify required parameter 'productName' is not null or undefined
            assertParamExists('updateProduct', 'productName', productName)
            // verify required parameter 'price' is not null or undefined
            assertParamExists('updateProduct', 'price', price)
            const localVarPath = `/api/Product/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


            if (productName !== undefined) { 
                localVarFormParams.append('ProductName', productName as any);
            }
    
            if (categoryId !== undefined) { 
                localVarFormParams.append('CategoryId', categoryId as any);
            }
    
            if (supplierId !== undefined) { 
                localVarFormParams.append('SupplierId', supplierId as any);
            }
    
            if (barcode !== undefined) { 
                localVarFormParams.append('Barcode', barcode as any);
            }
    
            if (price !== undefined) { 
                localVarFormParams.append('Price', price as any);
            }
    
            if (unit !== undefined) { 
                localVarFormParams.append('Unit', unit as any);
            }
    
            if (imageUrl !== undefined) { 
                localVarFormParams.append('ImageUrl', imageUrl as any);
            }
    
            if (imageFile !== undefined) { 
                localVarFormParams.append('ImageFile', imageFile as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProductApi - functional programming interface
 */
export const ProductApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProductApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} productName 
         * @param {number} price 
         * @param {number} [categoryId] 
         * @param {number} [supplierId] 
         * @param {string} [barcode] 
         * @param {string} [unit] 
         * @param {string} [imageUrl] 
         * @param {File} [imageFile] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createProduct(productName: string, price: number, categoryId?: number, supplierId?: number, barcode?: string, unit?: string, imageUrl?: string, imageFile?: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseProductResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createProduct(productName, price, categoryId, supplierId, barcode, unit, imageUrl, imageFile, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductApi.createProduct']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteProduct(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseObject>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteProduct(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductApi.deleteProduct']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [productName] 
         * @param {string} [barcode] 
         * @param {Array<number>} [categoryIds] 
         * @param {Array<number>} [supplierIds] 
         * @param {number} [minPrice] 
         * @param {number} [maxPrice] 
         * @param {boolean} [inStock] 
         * @param {number} [pageNumber] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async filterProducts(productName?: string, barcode?: string, categoryIds?: Array<number>, supplierIds?: Array<number>, minPrice?: number, maxPrice?: number, inStock?: boolean, pageNumber?: number, pageSize?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponsePagedResponseProductResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.filterProducts(productName, barcode, categoryIds, supplierIds, minPrice, maxPrice, inStock, pageNumber, pageSize, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductApi.filterProducts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [pageNumber] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllProducts(pageNumber?: number, pageSize?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponsePagedResponseProductResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllProducts(pageNumber, pageSize, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductApi.getAllProducts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} barcode 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProductByBarcode(barcode: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseProductResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProductByBarcode(barcode, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductApi.getProductByBarcode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProductById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseProductResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProductById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductApi.getProductById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {string} productName 
         * @param {number} price 
         * @param {number} [categoryId] 
         * @param {number} [supplierId] 
         * @param {string} [barcode] 
         * @param {string} [unit] 
         * @param {string} [imageUrl] 
         * @param {File} [imageFile] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProduct(id: number, productName: string, price: number, categoryId?: number, supplierId?: number, barcode?: string, unit?: string, imageUrl?: string, imageFile?: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseProductResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateProduct(id, productName, price, categoryId, supplierId, barcode, unit, imageUrl, imageFile, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductApi.updateProduct']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProductApi - factory interface
 */
export const ProductApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProductApiFp(configuration)
    return {
        /**
         * 
         * @param {ProductApiCreateProductRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProduct(requestParameters: ProductApiCreateProductRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResponseProductResponse> {
            return localVarFp.createProduct(requestParameters.productName, requestParameters.price, requestParameters.categoryId, requestParameters.supplierId, requestParameters.barcode, requestParameters.unit, requestParameters.imageUrl, requestParameters.imageFile, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProductApiDeleteProductRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProduct(requestParameters: ProductApiDeleteProductRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResponseObject> {
            return localVarFp.deleteProduct(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProductApiFilterProductsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        filterProducts(requestParameters: ProductApiFilterProductsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ResponsePagedResponseProductResponse> {
            return localVarFp.filterProducts(requestParameters.productName, requestParameters.barcode, requestParameters.categoryIds, requestParameters.supplierIds, requestParameters.minPrice, requestParameters.maxPrice, requestParameters.inStock, requestParameters.pageNumber, requestParameters.pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProductApiGetAllProductsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllProducts(requestParameters: ProductApiGetAllProductsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ResponsePagedResponseProductResponse> {
            return localVarFp.getAllProducts(requestParameters.pageNumber, requestParameters.pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProductApiGetProductByBarcodeRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProductByBarcode(requestParameters: ProductApiGetProductByBarcodeRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResponseProductResponse> {
            return localVarFp.getProductByBarcode(requestParameters.barcode, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProductApiGetProductByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProductById(requestParameters: ProductApiGetProductByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResponseProductResponse> {
            return localVarFp.getProductById(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProductApiUpdateProductRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProduct(requestParameters: ProductApiUpdateProductRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResponseProductResponse> {
            return localVarFp.updateProduct(requestParameters.id, requestParameters.productName, requestParameters.price, requestParameters.categoryId, requestParameters.supplierId, requestParameters.barcode, requestParameters.unit, requestParameters.imageUrl, requestParameters.imageFile, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createProduct operation in ProductApi.
 */
export interface ProductApiCreateProductRequest {
    readonly productName: string

    readonly price: number

    readonly categoryId?: number

    readonly supplierId?: number

    readonly barcode?: string

    readonly unit?: string

    readonly imageUrl?: string

    readonly imageFile?: File
}

/**
 * Request parameters for deleteProduct operation in ProductApi.
 */
export interface ProductApiDeleteProductRequest {
    readonly id: number
}

/**
 * Request parameters for filterProducts operation in ProductApi.
 */
export interface ProductApiFilterProductsRequest {
    readonly productName?: string

    readonly barcode?: string

    readonly categoryIds?: Array<number>

    readonly supplierIds?: Array<number>

    readonly minPrice?: number

    readonly maxPrice?: number

    readonly inStock?: boolean

    readonly pageNumber?: number

    readonly pageSize?: number
}

/**
 * Request parameters for getAllProducts operation in ProductApi.
 */
export interface ProductApiGetAllProductsRequest {
    readonly pageNumber?: number

    readonly pageSize?: number
}

/**
 * Request parameters for getProductByBarcode operation in ProductApi.
 */
export interface ProductApiGetProductByBarcodeRequest {
    readonly barcode: string
}

/**
 * Request parameters for getProductById operation in ProductApi.
 */
export interface ProductApiGetProductByIdRequest {
    readonly id: number
}

/**
 * Request parameters for updateProduct operation in ProductApi.
 */
export interface ProductApiUpdateProductRequest {
    readonly id: number

    readonly productName: string

    readonly price: number

    readonly categoryId?: number

    readonly supplierId?: number

    readonly barcode?: string

    readonly unit?: string

    readonly imageUrl?: string

    readonly imageFile?: File
}

/**
 * ProductApi - object-oriented interface
 */
export class ProductApi extends BaseAPI {
    /**
     * 
     * @param {ProductApiCreateProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createProduct(requestParameters: ProductApiCreateProductRequest, options?: RawAxiosRequestConfig) {
        return ProductApiFp(this.configuration).createProduct(requestParameters.productName, requestParameters.price, requestParameters.categoryId, requestParameters.supplierId, requestParameters.barcode, requestParameters.unit, requestParameters.imageUrl, requestParameters.imageFile, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProductApiDeleteProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteProduct(requestParameters: ProductApiDeleteProductRequest, options?: RawAxiosRequestConfig) {
        return ProductApiFp(this.configuration).deleteProduct(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProductApiFilterProductsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public filterProducts(requestParameters: ProductApiFilterProductsRequest = {}, options?: RawAxiosRequestConfig) {
        return ProductApiFp(this.configuration).filterProducts(requestParameters.productName, requestParameters.barcode, requestParameters.categoryIds, requestParameters.supplierIds, requestParameters.minPrice, requestParameters.maxPrice, requestParameters.inStock, requestParameters.pageNumber, requestParameters.pageSize, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProductApiGetAllProductsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllProducts(requestParameters: ProductApiGetAllProductsRequest = {}, options?: RawAxiosRequestConfig) {
        return ProductApiFp(this.configuration).getAllProducts(requestParameters.pageNumber, requestParameters.pageSize, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProductApiGetProductByBarcodeRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getProductByBarcode(requestParameters: ProductApiGetProductByBarcodeRequest, options?: RawAxiosRequestConfig) {
        return ProductApiFp(this.configuration).getProductByBarcode(requestParameters.barcode, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProductApiGetProductByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getProductById(requestParameters: ProductApiGetProductByIdRequest, options?: RawAxiosRequestConfig) {
        return ProductApiFp(this.configuration).getProductById(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProductApiUpdateProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateProduct(requestParameters: ProductApiUpdateProductRequest, options?: RawAxiosRequestConfig) {
        return ProductApiFp(this.configuration).updateProduct(requestParameters.id, requestParameters.productName, requestParameters.price, requestParameters.categoryId, requestParameters.supplierId, requestParameters.barcode, requestParameters.unit, requestParameters.imageUrl, requestParameters.imageFile, options).then((request) => request(this.axios, this.basePath));
    }
}

