/* tslint:disable */
/* eslint-disable */
/**
 * Store Management API
 * API for managing store operations including inventory, orders, and customers
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ResponseIEnumerablePromotionResponse } from '../models';
/**
 * PromotionApi - axios parameter creator
 */
export const PromotionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} [minOrderAmount] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllPromotions: async (minOrderAmount?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Promotion`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (minOrderAmount !== undefined) {
                localVarQueryParameter['minOrderAmount'] = minOrderAmount;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PromotionApi - functional programming interface
 */
export const PromotionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PromotionApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} [minOrderAmount] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllPromotions(minOrderAmount?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseIEnumerablePromotionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllPromotions(minOrderAmount, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PromotionApi.getAllPromotions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PromotionApi - factory interface
 */
export const PromotionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PromotionApiFp(configuration)
    return {
        /**
         * 
         * @param {PromotionApiGetAllPromotionsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllPromotions(requestParameters: PromotionApiGetAllPromotionsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ResponseIEnumerablePromotionResponse> {
            return localVarFp.getAllPromotions(requestParameters.minOrderAmount, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getAllPromotions operation in PromotionApi.
 */
export interface PromotionApiGetAllPromotionsRequest {
    readonly minOrderAmount?: number
}

/**
 * PromotionApi - object-oriented interface
 */
export class PromotionApi extends BaseAPI {
    /**
     * 
     * @param {PromotionApiGetAllPromotionsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllPromotions(requestParameters: PromotionApiGetAllPromotionsRequest = {}, options?: RawAxiosRequestConfig) {
        return PromotionApiFp(this.configuration).getAllPromotions(requestParameters.minOrderAmount, options).then((request) => request(this.axios, this.basePath));
    }
}

