/* tslint:disable */
/* eslint-disable */
/**
 * Store Management API
 * API for managing store operations including inventory, orders, and customers
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ResponseIEnumerableRevenueResponse } from '../models';
// @ts-ignore
import type { ResponseIEnumerableTopSellerProductResponse } from '../models';
/**
 * StatisticApi - axios parameter creator
 */
export const StatisticApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} [year] 
         * @param {number} [month] 
         * @param {number} [day] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDailyRevenue: async (year?: number, month?: number, day?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Statistic/revenue`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (year !== undefined) {
                localVarQueryParameter['year'] = year;
            }

            if (month !== undefined) {
                localVarQueryParameter['month'] = month;
            }

            if (day !== undefined) {
                localVarQueryParameter['day'] = day;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} top 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTopSellerProduct: async (top: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'top' is not null or undefined
            assertParamExists('getTopSellerProduct', 'top', top)
            const localVarPath = `/api/Statistic/top-seller/{top}`
                .replace(`{${"top"}}`, encodeURIComponent(String(top)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StatisticApi - functional programming interface
 */
export const StatisticApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StatisticApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} [year] 
         * @param {number} [month] 
         * @param {number} [day] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDailyRevenue(year?: number, month?: number, day?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseIEnumerableRevenueResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDailyRevenue(year, month, day, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatisticApi.getDailyRevenue']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} top 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTopSellerProduct(top: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseIEnumerableTopSellerProductResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTopSellerProduct(top, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatisticApi.getTopSellerProduct']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * StatisticApi - factory interface
 */
export const StatisticApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StatisticApiFp(configuration)
    return {
        /**
         * 
         * @param {StatisticApiGetDailyRevenueRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDailyRevenue(requestParameters: StatisticApiGetDailyRevenueRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ResponseIEnumerableRevenueResponse> {
            return localVarFp.getDailyRevenue(requestParameters.year, requestParameters.month, requestParameters.day, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {StatisticApiGetTopSellerProductRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTopSellerProduct(requestParameters: StatisticApiGetTopSellerProductRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResponseIEnumerableTopSellerProductResponse> {
            return localVarFp.getTopSellerProduct(requestParameters.top, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getDailyRevenue operation in StatisticApi.
 */
export interface StatisticApiGetDailyRevenueRequest {
    readonly year?: number

    readonly month?: number

    readonly day?: number
}

/**
 * Request parameters for getTopSellerProduct operation in StatisticApi.
 */
export interface StatisticApiGetTopSellerProductRequest {
    readonly top: number
}

/**
 * StatisticApi - object-oriented interface
 */
export class StatisticApi extends BaseAPI {
    /**
     * 
     * @param {StatisticApiGetDailyRevenueRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDailyRevenue(requestParameters: StatisticApiGetDailyRevenueRequest = {}, options?: RawAxiosRequestConfig) {
        return StatisticApiFp(this.configuration).getDailyRevenue(requestParameters.year, requestParameters.month, requestParameters.day, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {StatisticApiGetTopSellerProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTopSellerProduct(requestParameters: StatisticApiGetTopSellerProductRequest, options?: RawAxiosRequestConfig) {
        return StatisticApiFp(this.configuration).getTopSellerProduct(requestParameters.top, options).then((request) => request(this.axios, this.basePath));
    }
}

