import type { Metadata } from "next";
// @ts-ignore: side-effect CSS import has no type declaration in this project
import "./globals.css";
import SidebarClient from "../components/sidebar-client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="">
        {/* Client-managed sidebar; it updates --sidebar-width on :root */}
        <SidebarClient />
        <main
          className="min-h-screen transition-all duration-200 p-6"
          style={{ marginLeft: "var(--sidebar-width, 14rem)" }}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
