"use client";

import type { Metadata } from "next";
// @ts-ignore: side-effect CSS import has no type declaration in this project
import "./globals.css";
import SidebarClient from "../components/sidebar-client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "sonner";
import { AuthProvider, useAuth } from "./lib/auth/auth-context";
import AuthGuard from "../components/auth-guard";
import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const client = new QueryClient();

function LayoutContent({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const isLoginPage = pathname === "/login";

  if (isLoginPage) {
    return <main className="min-h-screen">{children}</main>;
  }

  return (
    <>
      <SidebarClient />
      <main
        className="min-h-screen transition-all duration-200 p-6"
        style={{ marginLeft: "var(--sidebar-width, 14rem)" }}
      >
        {children}
      </main>
    </>
  );
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="">
        <QueryClientProvider client={client}>
          <AuthProvider>
            <AuthGuard>
              <Toaster position="top-right" richColors />
              <LayoutContent>{children}</LayoutContent>
            </AuthGuard>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
